environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"

  # only build CPython-3.6 and later
  CIBW_BUILD: cp3?-*
  CIBW_SKIP: cp35-*
  CIBW_BEFORE_ALL: |
    choco install swig -y
  CIBW_BEFORE_BUILD: |
    python -m pip install numpy
  CIBW_TEST_COMMAND: |
    python {project}/extern/nlopt/test/t_python.py

stack: python 3.7

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install cibuildwheel==1.5.1

build_script: python -m cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
