name: Build

on:
  pull_request:
    branches:
      - master

concurrency:
  cancel-in-progress: false
  group: build-pr-${{ github.event.pull_request.number }}

jobs:
  build:
    name: Build & test wheels
    uses: ./.github/workflows/wc-build.yml
    permissions:
      id-token: write
      contents: read
    with:
      os: "windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-latest,macos-14"
      python-versions: "3.10,3.11,3.12,3.13,3.14"
      target: testpypi
